# README:
# - When changing the module name, it needs to be changed in 'env:MODULE_NAME' and in 'on:pull_requests:path'!
#
# Resources:
# - Template for this file: https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml
# - About Ansible integration tests: https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html

env:
  NAMESPACE: checkmk
  COLLECTION_NAME: general

name: Ansible Integration Tests for all Modules
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  integration:
    runs-on: ubuntu-latest
    name: ${{ matrix.module }} (Ⓐ${{ matrix.ansible }}+py${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.13
          - stable-2.14
          - stable-2.15
          - devel
        python:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
        module:
          - activation
          - bakery
          - contact_group
          - discovery
          - downtime
          - folder
          - host_group
          - host
          - password
          - rule
          - service_group
          - tag_group
          - user
        exclude:
          # Exclude unsupported sets.
          - ansible: stable-2.13
            python: '3.11'

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Ansible 2.13 does not support Python 3.11.

      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Provide secrets file
        run: echo "${{ secrets.CHECKMK_DOWNLOAD_PW }}" > ./tests/integration/files/.dl-secret
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
        env:
          CHECKMK_DOWNLOAD_PW: ${{ secrets.CHECKMK_DOWNLOAD_PW }}

      - name: Run integration test
        run: ansible-test integration ${{ matrix.module }} -v --color --retry-on-error --continue-on-error --diff --python ${{ matrix.python }} --docker --coverage
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
