# README:
# Resources:
# - Template for this file: https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml
# - About Ansible sanity tests: https://docs.ansible.com/ansible/latest/dev_guide/testing_sanity.html

env:
  NAMESPACE: checkmk
  COLLECTION_NAME: general

name: Ansible Sanity Tests
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*'
      - 'docs/**'
      - 'changelogs/**'
      - '**.md'
      - '**.rst'
      - 'roles/**'
  pull_request:
    types: [opened]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*'
      - 'docs/**'
      - 'changelogs/**'
      - '**.md'
      - '**.rst'
      - 'roles/**'

jobs:

  sanity:
    runs-on: ubuntu-latest
    name: Sanity (Ⓐ${{ matrix.ansible }})
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.13
          - stable-2.14
          - stable-2.15
          - devel

    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ansible 2.13 does not support Python 3.11.

      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color --coverage
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
