name: Python QA

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
jobs:
  run-qa:
    name: Run QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements-qa.txt
      - name: Install linters
        run: python -m pip install -r requirements-qa.txt
      - name: Check format
        run: black --check --diff plugins
        if: always()
      - name: Check imports
        run: isort --check --diff plugins
        if: always()
